name: Update TRN Types and Create PR

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
    inputs:
      network:
        description: 'Network to use for metadata update, "porcini" or "mainnet"'
        required: true
        type: choice
        options:
          - porcini
          - mainnet
        default: porcini

jobs:
  update-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to create a new branch

      - name: Set up Node.js and install pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Run update and generate commands
        run: |
          pnpm --filter=@therootnetwork/api-types update:meta -- --network=${{ github.event.inputs.network }}
          pnpm --filter=@therootnetwork/api-types generate:types
          pnpm --filter=@therootnetwork/api test:snapshot
          pnpm format

      - name: Create new branch and commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="chore/update-api-types-${{ github.event.inputs.network }}-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          
          git add .
          git commit -m "chore: update API types for ${{ github.event.inputs.network }}"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: update API types for ${{ github.event.inputs.network }}"
          body: "This PR was automatically generated by a workflow to update TRN API types for the ${{ github.event.inputs.network }} network."
          head: ${{ steps.create.outputs.branch }}
          base: main
