name: Update TRN Types and Create PR

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network to use for metadata update, "porcini" or "mainnet"'
        required: true
        type: choice
        options:
          - porcini
          - mainnet
        default: porcini

permissions:
  contents: write
  pull-requests: write

jobs:
  update-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run update and generate commands
        run: |
          pnpm --filter=@therootnetwork/api-types update:meta -- --network=${{ github.event.inputs.network }}
          pnpm --filter=@therootnetwork/api-types generate:types
          pnpm --filter=@therootnetwork/api test:snapshot
          pnpm format

      - name: Check for changes
        id: check_changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.DEV_TEAM_USED_PAT }}
          commit-message: "Update API types from ${{ github.event.inputs.network }}"
          title: "Update API types from ${{ github.event.inputs.network }}"
          body: "This PR was automatically generated based on metadata from `${{ github.event.inputs.network }}`."
          branch: chore/update-api-types-${{ github.event.inputs.network }}-${{ github.run_id }}
          base: main
